MODEL_NAME_LLM: meta-llama/Llama-3-8b-hf

ALIAS: default
MILVUS_HOST: http://localhost #http://10.198.0.4 #
MILVUS_PORT: 19530
# MILVUS_TOKEN: root:Milvus
LOGGING_LEVEL: INFO
N_FOR_PROMPT: 30
TRESHOLD_DIRECT_ACCEPT: 0.95
TRESHOLD_CANDIDATE_ACCEPT: 0.95
DEVICE: cpu


COSISTENCY_LEVEL: Session
PORT: 8031

